[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer update --no-dev --optimize-autoloader --with-all-dependencies"]

[start]
cmd = "cd /app && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
